# -*- coding: utf-8 -*-
"""VERIFIED REAL-HUMAN LISTENING SOURCES FOR THE DIAGNOSTIC PAPERS.

Ten VOA *Let’s Learn English* Level 1 episodes that the 92 teaching sessions do
NOT use.  A baseline test cannot be built from material the students are about to
study, so these were sourced separately and put through the same checks as the 89
course recordings: page fetched, published transcript extracted, audio downloaded,
duration / bitrate / sample rate / channels read with ffprobe, mean and peak levels
measured with ffmpeg volumedetect, speech rate computed from transcript words over
the measured duration.

VOA material is public domain, which is the reason only VOA was used here: unlike the
ELLLO half of the course corpus it may legally be printed inside a test paper.

No audio in this file is synthetic, and none of it was recorded by the teacher.
"""
from .schema import A

DIAG_AUDIO = {}

# --------------------------------------------------------------------------
# D1_1  VOA Lesson 5: Where Are You?  (1:00, 104 wpm)
DIAG_AUDIO['D1_1'] = A(
    'Lesson 5: Where Are You?',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. It lasts 1:00.',
    [
        'Anna: Hello, everyone! Today my friend Marsha is at her friend\'s house. She says it is beautiful. I want to see this house! Here we are!',
        'Anna: Marsha, I am in the kitchen! It is a beautiful kitchen!',
        'Marsha: It is beautiful. We cook in the kitchen.',
        'Anna: I eat in the kitchen.',
        'Marsha: We relax in the living room.',
        'Anna: I relax in the living room. Marsha, let’s go upstairs!',
        'Marsha: Anna? Where are you?',
        'Anna: Marsha, I am in the bathroom! I wash in the bathroom.',
        'Marsha: I am in the bedroom. We sleep in the bedroom.',
        'Anna: I sleep in the bedroom!',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-5-where-are-you/3168971.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/03/01/ab9c2944-eddc-4806-9296-290bfa8c6ff2_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='1:00',
    speech_rate='104 words per minute as heard',
    level='pre-A1 / A1',
    script_is_excerpt=False,
    teacher_note='LOCAL FILE: audio/FD1_1_ab9c2944-eddc-4806-9296-290bfa8c6ff2_hq.mp3. The floor item. Ten short turns, 104 wpm, six rooms of a house and six present-simple verbs. A student who cannot answer this has not consolidated Grade 5 English.',
)

# --------------------------------------------------------------------------
# D1_2  VOA Lesson 10: Come Over to My Place  (1:30, 108 wpm)
DIAG_AUDIO['D1_2'] = A(
    'Lesson 10: Come Over to My Place',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. It lasts 1:30.',
    [
        'Anna: Hi! Today, my friend Ashley, is coming over. I am showing her my new apartment! Oh! That’s Ashley calling.',
        'Anna: Hi Ashley!',
        'Ashley: Hi Anna! I’m coming to your apartment. Where is your apartment?',
        'Anna: My apartment is near the Columbia Heights Metro.',
        'Ashley: It is near the Columbia Heights Metro?',
        'Anna: Yes. Exit the Metro and turn right. Then at the bus station turn left. Then walk straight ahead.',
        'Ashley: Okay. Exit Metro, turn right, turn left, then go straight ahead?',
        'Anna: Yes. My apartment is near a coffee shop.',
        'Ashley: Okay. See you soon!',
        'Anna: Hi, Ashley.',
        'Ashley: Anna, Which coffee shop? There are three coffee shops.',
        'Anna: Okay, my apartment is across from a big department store.',
        'Ashley: A big department store? Ah, I see it!',
        'Anna: Okay! Bye, Ashley. See you soon!',
        'Ashley: Okay. See you soon.',
        'Anna: Ashley! Ashley! Ashley! Over here! It’s Anna! It’s Anna! Hi!',
        'Anna: I love having my friends over. Come on!',
        'Ashley: Great!',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-10/3285228.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/04/14/442a6a50-693e-411f-8cff-99e40d16614c_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='1:30',
    speech_rate='108 words per minute as heard',
    level='A1',
    script_is_excerpt=False,
    teacher_note='LOCAL FILE: audio/FD1_2_442a6a50-693e-411f-8cff-99e40d16614c_hq.mp3. The at-level item. Directions, prepositions of place and there is / there are at 108 wpm — the language a Vietnamese student is expected to bring into Grade 7.',
)

# --------------------------------------------------------------------------
# D1_3  VOA Lesson 27: I Can't Come In  (1:16, 140 wpm, excerpt)
DIAG_AUDIO['D1_3'] = A(
    'Lesson 27: I Can\'t Come In',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. You will hear only the first part of it, about 1:16 long.',
    [
        'Anna: Hello! I am sure that today, in Washington, D.C,. there are a lot of great things to do. But I am not doing any of them. I am sick. Right now, I\'m going to call my boss and tell her I cannot come in to work.',
        'Caty: Hello?',
        'Anna: Ms. Weaver, Hi. I can’t come to work today.',
        'Caty: Why not? What is wrong?',
        'Anna: Well, yesterday I felt fine.',
        'Anna: In the morning, I painted for hours. In the afternoon, I cut wood. Then, I built a fire.',
        'Caty: Anna, what do you mean? Why can’t you come to work today?',
        'Anna: I do not feel well. I think I’m sick.',
        'Caty: I’m sorry to hear that. I was sick last week, too. I had the flu.',
        'Anna: (sneezes) What did you do?',
        'Caty: I slept a lot and I drank a lot of water. Do you have a doctor?',
        'Anna: Yes, I do.',
        'Caty: You should call your doctor. And get lots of rest!',
        'Anna: Thanks, Ms. Weaver. I’ll call right now. I\'m calling my doctor.',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-27-i-cant-come-in/3457316.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/08/30/4b0918a8-33b1-4b9d-8d88-f54d8a1be9ea_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='1:16',
    speech_rate='140 words per minute as heard',
    level='A2',
    script_is_excerpt=True,
    teacher_note='LOCAL FILE: audio/FD1_3_4b0918a8-33b1-4b9d-8d88-f54d8a1be9ea_hq.mp3. Play 0:00–1:20 only. Stop the recording after Anna says “I’ll call right now. I’m calling my doctor.” The ceiling item. 140 wpm, past simple (felt, painted, cut, built, slept, drank, had), should for advice, and a telephone register. Only students already at A2 will get all four.',
)

# --------------------------------------------------------------------------
# M1_1  VOA Lesson 4: What Is It?  (1:29, 125 wpm)
DIAG_AUDIO['M1_1'] = A(
    'Lesson 4: What Is It?',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. It lasts 1:29.',
    [
        'Anna: Pete, hi! Hi, we are here!',
        'Pete: Hi, Anna! Hi, Marsha!',
        'Anna: Hi!',
        'Pete: How are you two?',
        'Marsha: I am great!',
        'Anna: You know, Pete, I am new to D.C. The city is big.',
        'Pete: Yeah. But you learn a little more every day. How\'s the new apartment?',
        'Anna: The new apartment is great! Let\'s get coffee!',
        'Marsha: Anna, do you have a pen?',
        'Anna: Yes. I have a pen in my bag.',
        'Anna: I have a …',
        'Pete: It is not a pen. It is a book. It is a big book.',
        'Anna: Yes. Yes it is, Pete. I know I have a pen, though…',
        'Anna: I have a ....',
        'Marsha: It is not a pen, Anna ... a toy?',
        'Anna: I have a ....',
        'Pete: And it is a pillow!',
        'Anna: Pete, Marsha, I know I have a pen.',
        'Marsha: Anna, it is a map.',
        'Pete: Why do you have a map of the world?',
        'Anna: Pete, Marsha. Now I know I have a pen.',
        'Pete: And now you have a lamp.',
        'Marsha: Anna.',
        'Anna: I have a pen! Let’s get coffee!',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-4/3168920.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/02/26/af0324f6-67c5-4c0c-ab42-abb0cd33817c_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='1:29',
    speech_rate='125 words per minute as heard',
    level='A1',
    script_is_excerpt=False,
    teacher_note='LOCAL FILE: audio/FM1_1_af0324f6-67c5-4c0c-ab42-abb0cd33817c_hq.mp3. Mid-year floor: a / an, it is / it is not, and eight concrete nouns at 125 wpm.',
)

# --------------------------------------------------------------------------
# M1_2  VOA Lesson 32: Welcome to the Treehouse!  (1:38, 124 wpm, excerpt)
DIAG_AUDIO['M1_2'] = A(
    'Lesson 32: Welcome to the Treehouse!',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. You will hear only the first part of it, about 1:38 long.',
    [
        'Anna: Hello! Today is a big day. My first children’s show is on television! Woo-hoo! I’m excited and nervous.',
        'Ms. Weaver: Hello, Anna.',
        'Anna: Hello, Ms. Weaver!',
        'Ms. Weaver: Some people are going to watch your children’s show. After they watch it, they’ll tell me what they liked, and what they didn’t like.',
        'Anna: Oh, dear.',
        'Ms. Weaver: They’re in the conference room. They’re in the conference room.',
        'Anna: Hello, everyone. I’m Anna, and thanks for coming!',
        'Anna: Today you are going to watch my new show. I hope you like it',
        'Coworker 2: What is the show about?',
        'Anna: It’s a children’s show.',
        'Coworker 1: But we are not children!',
        'Anna: This children\'s show is different. I hope.',
        'Coworker 3: I don’t really like children\'s shows.',
        'Anna: Shhh, please. The show is starting!',
        'Anna: Oh, hi! Just give me one minute ….oops! Oh well. I can fix that later.',
        'Anna: Hello, I’m Anna! Welcome to “The Time Traveling Treehouse!” This is not a usual treehouse. It can time travel! That is why it’s called "The Time Traveling Treehouse."',
        'MINDY: Anna, do not forget me.',
        'Anna: Of course not! This is my partner, MINDY!',
        'MINDY: My name means Massive Information Navigation Device, for You!',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-32-welcome-treehouse/3547306.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/10/13/054d9504-47b3-4cc2-80d1-cb66fff404e4_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='1:38',
    speech_rate='124 words per minute as heard',
    level='A2',
    script_is_excerpt=True,
    teacher_note='LOCAL FILE: audio/FM1_2_054d9504-47b3-4cc2-80d1-cb66fff404e4_hq.mp3. Play 0:00–1:40 only. Stop the recording after MINDY says “My name means Massive Information Navigation Device, for You!” Mid-year ceiling: going to and will inside a narrative at 124 wpm. Both forms are taught later in the year, which is exactly why they belong in a ceiling item.',
)

# --------------------------------------------------------------------------
# F1_1  VOA Lesson 9: Is It Cold?  (2:01, 104 wpm)
DIAG_AUDIO['F1_1'] = A(
    'Lesson 9: Is It Cold?',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. It lasts 2:01.',
    [
        'Anna: Oh, hi, everyone! Here in Washington, DC, the weather changes often. One day is cold and windy. But the next day is warm and sunny! So, every day I check the forecast. Hello, Phone? What is today’s temperature?',
        'Phone: Today it is 18 degrees ...',
        'Anna: Eighteen degrees! That is cold!',
        'Phone: … eighteen degrees Celsius.',
        'Anna: Oh, Celsius. That is 65 degrees Fahrenheit. That’s warm.',
        'Phone: Yes, Anna. It is warm.',
        'Anna: Excuse me, Phone. Is it windy today?',
        'Phone: No, it is not windy today.',
        'Anna: Is it sunny today?',
        'Phone: Yes, Anna. It is sunny.',
        'Anna: Excuse me, Phone?',
        'Phone: Yes, Anna.',
        'Anna: Is it snowy today?',
        'Phone: No, Anna. It is not snowy.',
        'Anna: Thank you, Phone!',
        'Anna: Today the weather is warm and sunny -- great for seeing Washington, D.C.',
        'Anna: Phone! It is not warm and sunny! It is cold and windy and snowy!',
        'Phone: Anna, it is not cold, windy, or snowy. It is warm and sunny … in Mexico City, Mexico.',
        'Anna: Oh. I see. Mexico.',
        'Anna: Washington weather changes often. Remember to check the forecast -- the right forecast.',
        'Phone: Yes, Anna. Next time remember to check the right fore…',
        'Anna: Okay, thank you Phone. Goodbye, Phone.',
        'Anna: Until next time!',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-9-is-it-cold/3261789.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/04/01/fe67e651-87d0-4b62-9c68-749b2d3c2f21_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='2:01',
    speech_rate='104 words per minute as heard',
    level='A1',
    script_is_excerpt=False,
    teacher_note='LOCAL FILE: audio/FF1_1_fe67e651-87d0-4b62-9c68-749b2d3c2f21_hq.mp3. Parallel to D1.1: same 104 wpm, same yes/no question-and-answer shape, weather instead of rooms, plus one inference (the forecast is for Mexico City, not Washington).',
)

# --------------------------------------------------------------------------
# F1_2  VOA Lesson 8: Are You Busy?  (1:58, 105 wpm)
DIAG_AUDIO['F1_2'] = A(
    'Lesson 8: Are You Busy?',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. It lasts 1:58.',
    [
        'Anna: Hello, everyone. Here I am at my new job! Yesterday at my first day of work … Well, let’s not talk about yesterday. Today is a new day! Today I want to apologize to my co-workers.',
        'Anna: Hi, Anne. Are you busy?',
        'Anne: Hi, Anna. Yes. At 10 a.m. I am writing. Every day I do my morning show. Sorry!',
        'Anna: Okay. See you later, maybe.',
        'Anne: Maybe I’ll see you later.',
        'Anna: Hi, Jonathan. Are you busy?',
        'Jonathan: Yes, I’m busy. When the studio light is on, I am recording my evening show.',
        'Anna: Right. Sorry about yesterday.',
        'Jonathan: No worries.',
        'Anna: May I see the studio?',
        'Jonathan: Um, maybe another time? Right now I am busy.',
        'Anna: Sure. Okay, ’bye.',
        'Jonathan: ‘Bye.',
        'Anna: Hi, Amelia! Are you busy?',
        'Amelia: I’m a little busy.',
        'Anna: I want to say I’m sorry for yesterday.',
        'Amelia: It’s okay, Anna.',
        'Anna: Well, I am sorry.',
        'Amelia: It’s okay, Anna. Come by this afternoon.',
        'Anna: Okay.',
        'Caty: Anna.',
        'Anna: Yes, Ms. Weaver.',
        'Caty: Are you busy?',
        'Anna: Yes, Ms. Weaver. I am busy.',
        'Caty: My office. 5:00 p.m.',
        'Anna: 5:00 p.m.',
        'Caty: Come in.',
        'Co-Workers: Surprise!',
        'Anna: A party! Awesome! And I still have my job! Phew!* Until next time!',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-8-are-you-busy/3253185.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/03/25/ae6c5055-13ae-485b-995d-b347125ecf10_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='1:58',
    speech_rate='105 words per minute as heard',
    level='A1+',
    script_is_excerpt=False,
    teacher_note='LOCAL FILE: audio/FF1_2_ae6c5055-13ae-485b-995d-b347125ecf10_hq.mp3. Parallel to D1.2: 113 wpm, a repeated question frame (Are you busy?) with present continuous answers and clock times.',
)

# --------------------------------------------------------------------------
# F1_3  VOA Lesson 38: She's My Best Friend!  (1:20, 124 wpm, excerpt)
DIAG_AUDIO['F1_3'] = A(
    'Lesson 38: She\'s My Best Friend!',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. You will hear only the first part of it, about 1:20 long.',
    [
        'Anna: Hello! I have great news. My best friend from my hometown is coming here -- to Washington, D.C.! I can’t wait to catch up with her! Oh! I gotta go. Her train arrives in 10 minutes!',
        'Anna: Penelope!',
        'Penelope: Anna! I am really happy to see you!',
        'Anna: Me too! How was your trip?',
        'Penelope: It was fine.',
        'Anna: Let me help you with your bags.',
        'Penelope: I’m really excited to be in Washington, D.C.! I can’t wait to hear about … everything!',
        'Anna: I have so much to tell you. Let’s go to my apartment. We can talk over a hot cup of tea.',
        'Penelope: I love your apartment building, Anna. Is your rent expensive?',
        'Anna: Well, I have a roommate. So, we split the rent.',
        'Penelope: Oh, that’s right. Is your roommate nice?',
        'Anna: Marsha is the nicest person I know in this city. Sometimes she worries too much. And she says I’m the messiest cook she knows. But we are great roommates.',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-38-shes-my-best-friend/3591967.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/12/01/7b357de6-9247-45fd-8e49-77197599f6d5_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='1:20',
    speech_rate='124 words per minute as heard',
    level='A2',
    script_is_excerpt=True,
    teacher_note='LOCAL FILE: audio/FF1_3_7b357de6-9247-45fd-8e49-77197599f6d5_hq.mp3. Play 0:00–1:20 only. Stop the recording after Anna says “But we are great roommates.” Parallel to D1.3: 124 wpm, superlatives (the nicest, the messiest) and a social conversation about rent and roommates.',
)

# --------------------------------------------------------------------------
# BRIDGE  VOA Lesson 33: Learning America's Sport  (3:48, 88 wpm)
DIAG_AUDIO['BRIDGE'] = A(
    'Lesson 33: Learning America\'s Sport',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. It lasts 3:48.',
    [
        'Announcer: Last time on "The Time Traveling Treehouse," Anna was lost, really lost. She wants to learn about baseball. But her computer, MINDY, sent her to many wrong places.',
        'Anna: MINDY! Help me! I am in the ocean with a shark!',
        'MINDY: I will try one more time, Anna.',
        'Anna: Please try harder, MINDY!',
        'Anna: Now, where am I? I am at a playground with a baseball field! Yes! I can teach children about baseball here! MINDY, MINDY, it took you a long time. But you did it!',
        'MINDY: Thanks, Anna. Give me a call when you find the answer.',
        'Anna: Okay. Come with me. Let’s learn how to play baseball! This is a baseball field. This is a pitcher\'s mound. This is first base! This is second base! This is third base! This is home plate!',
        'Anna: To play baseball, you really only need a bat, a ball and a glove. Each team has many players.',
        'Pitchers pitch the ball.',
        'Catchers catch the ball.',
        'Batters bat the ball.',
        'Runners run the bases.',
        'Fielders field the ball.',
        'Anna: First, the pitcher pitches the ball to the batter. The batter bats the ball. Then, the runner runs to first base.',
        'Anna: Each time a batter bats, the runners run around the bases. Each time a runner runs across home plate, they score a run! There are nine innings in a game. The team with the most runs at the end of nine innings wins the game!',
        'Anna: MINDY, MINDY, we found the answer! It’s time to return to the treehouse.',
        'MINDY: Good job! That was fast.',
        'Coworker 3: Good job Anna. You know, I still don\'t like children\'s shows, but I like this children\'s show.',
        'Coworker 2: I liked the time travel.',
        'Coworker 1: But time travel is not real. You’re so silly, Anna.',
        'Anna: Yeah, time travel is so silly. Thanks, goodbye. Bye, thank you.',
        'Anna: Hello, MINDY? Are you there?',
        'MINDY: Hello, Anna.',
        'Anna: MINDY, I want to go to China! Until next time …',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lesson-33-learning-americas-sport/3555047.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2016/10/21/f7144253-3403-4acd-9e09-9c31443113f7_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='3:48',
    speech_rate='88 words per minute as heard',
    level='A1 — slow',
    script_is_excerpt=False,
    teacher_note='LOCAL FILE: audio/FBRIDGE_1_f7144253-3403-4acd-9e09-9c31443113f7_hq.mp3. 88 words per minute: the slowest recording in the whole corpus, course and diagnostic together. Used with the Foundation group, whose problem is usually speed, not vocabulary. Heavily sequenced (First… Then… Each time…), so it also teaches listening for order.',
)

# --------------------------------------------------------------------------
# EXT  VOA Lesson 42: I Was Minding My Own Business  (3:01, 153 wpm)
DIAG_AUDIO['EXT'] = A(
    'Lesson 42: I Was Minding My Own Business',
    'You will hear a real recording from VOA Learning English. American English, professional actors, slowed learner delivery. It lasts 3:01.',
    [
        'Guy: Hello. I\'m Guy Newsman with News Channel XYZ. I’m here in Washington, D.C. at the scene of a crime.',
        'Guy: We are talking with this woman.',
        'Guy: She saw the crime during her lunch break. It looks like she hurt herself while she was trying to stop the crime.',
        'Guy: Tell us your name.',
        'Anna: Hi, Guy. I\'m Anna.',
        'Guy: Anna, what did you see and what happened to your arm?',
        'Anna: Guy, I was minding my own business. See, I work over there.',
        'Guy: Um-hum',
        'Anna: I left work to get some lunch. Then suddenly, I heard a woman yelling. She was yelling like this ... “Help! Help!”',
        'Guy: Um-hum',
        'Anna: Two robbers were grabbing her bag like this. She was hitting them with her umbrella.',
        'Guy: Is that when you hurt your arm?',
        'Anna: No. At that time, I was not fighting the robbers.',
        'Guy: Um-hum.',
        'Anna: See. I was too far away and I didn\'t have my own umbrella.',
        'Guy: So, what happened next?',
        'Anna: They grabbed her bag and ran away! So, I grabbed her umbrella and ran after the robbers.',
        'Guy: Then that is the time that you hurt your arm?',
        'Anna: No. I was yelling, “Stop, robbers! Stop!” She was yelling, “Hey, come back with my umbrella!”',
        'Guy: Were you afraid?',
        'Anna: I had no time to be afraid, Guy. Well, I had time while I was resting on a bench. I had a lot of time.',
        'Guy: Then what happened?',
        'Anna: The robbers got on a bus. So, I ran after the bus.',
        'A VO: While I was running, I tripped and fell.',
        'Guy: And that is the time that you hurt your arm?',
        'Anna: No. While I was lying on the ground, someone stepped on my arm!',
        'Guy: Ouch. That’s too bad.',
        'Anna: Yeah. And they didn’t apologize. Well, then the robbers got themselves kicked off the bus.',
        'Guy: Why?',
        'Anna: They didn’t pay. You\'ve got to pay when you get on a bus. The police came and took them away.',
        'Guy: And that’s when you hurt your arm!',
        'Anna: No.',
        'Guy: Then, when did you hurt yourself?',
        'Anna: Well, Guy, by this time, I was feeling very hungry. So, I went to my office to get a snack.',
        'C: Anna, I\'m calling for help right now.',
        'C: (on the phone) Hello? Yes, please come right away. My co-worker is stuck in a vending machine.',
        'Guy: You hurt your arm in a vending machine buying a bag of chips?',
        'Anna: I was really hungry and the bag was stuck. I had to -',
        'Guy: That’s all from News Channel XYZ. This is Guy Newsman saying goodbye.',
        'Guy: Okay, we have to find ourselves another story, guys.',
        'Anna: Until next time! Hi Mom!',
    ],
    source='VOA Learning English — Let’s Learn English, Level 1',
    source_page='https://learningenglish.voanews.com/a/lets-learn-english-lesson-42-i-was-minding-my-own-business/3647264.html',
    audio_urls=['https://voa-audio.voanews.eu/vle/2017/01/12/51393a0f-7412-4703-8f47-866cfd57955c_hq.mp3'],
    licence='Public domain. Material produced exclusively by VOA is in the public domain: it may be downloaded, copied, played in class and printed in test papers, with credit to VOA.',
    attribution='Voice of America — “Let’s Learn English, Level 1” · learningenglish.voanews.com · public domain',
    speakers='American English — VOA’s professional actors (Anna, Marsha, Pete, Ms. Weaver…), slowed learner delivery written for beginners',
    duration='3:01',
    speech_rate='153 words per minute as heard',
    level='A2+ / B1',
    script_is_excerpt=False,
    teacher_note='LOCAL FILE: audio/FEXT_1_51393a0f-7412-4703-8f47-866cfd57955c_hq.mp3. 153 words per minute, a news-interview register, and past continuous throughout — a form the Grade 7 syllabus never teaches. The fastest recording in the corpus, kept for the Extension group.',
)


# Local file for every key, relative to the project root.  Every one of these was
# downloaded and probed; none is a placeholder.
DIAG_FILES = {
    'D1_1': 'audio/FD1_1_ab9c2944-eddc-4806-9296-290bfa8c6ff2_hq.mp3',
    'D1_2': 'audio/FD1_2_442a6a50-693e-411f-8cff-99e40d16614c_hq.mp3',
    'D1_3': 'audio/FD1_3_4b0918a8-33b1-4b9d-8d88-f54d8a1be9ea_hq.mp3',
    'M1_1': 'audio/FM1_1_af0324f6-67c5-4c0c-ab42-abb0cd33817c_hq.mp3',
    'M1_2': 'audio/FM1_2_054d9504-47b3-4cc2-80d1-cb66fff404e4_hq.mp3',
    'F1_1': 'audio/FF1_1_fe67e651-87d0-4b62-9c68-749b2d3c2f21_hq.mp3',
    'F1_2': 'audio/FF1_2_ae6c5055-13ae-485b-995d-b347125ecf10_hq.mp3',
    'F1_3': 'audio/FF1_3_7b357de6-9247-45fd-8e49-77197599f6d5_hq.mp3',
    'BRIDGE': 'audio/FBRIDGE_1_f7144253-3403-4acd-9e09-9c31443113f7_hq.mp3',
    'EXT': 'audio/FEXT_1_51393a0f-7412-4703-8f47-866cfd57955c_hq.mp3',
}
